### ISSUE TITLE
Much more constants can be  found in pwntools

### ISSUE THREAD

**Issue by matrix1001** [zTrix/magic#2]
This project is amazing.
If u are seeking more magic numbers, check pwntools.
Many constants of various arch can be found in its source code. But u can only find its value if u know its name.
However, ur project is much more helpful than that.

**Comment by zTrix** [comment]
Yes you are right.

I built this project with initial idea and framework, as well as a few constants I found, but while I'm too lazy, it's hard for me to collect them all.

Pwntools is much more powerful, I also recommend this tool.
